[ { name: 'Ahrar ash-Sham',
    allies: 
     [ 'al-Nusra Front',
       'Jaysh al-Islam',
       'Ajnad al-Sham Islamic Union',
       'Army of Mujahedeen',
       'Alweiat Al-Furqan',
       'Sham Legion',
       'Suqour al-Ezz',
       'Harakat Sham al-Islam',
       'Jaish al-Muhajireen wal-Ansar',
       'Ahrar al-Jazeera' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Resistance',
       'Syriac Military Council',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant',
       'United States Armed Forces' ],
    partof: 
     [ 'Islamic Front (Syria)',
       'Syrian Revolutionary Command Council',
       'Army of Conquest',
       'Fatah Halab',
       'Unified Military Command of Eastern Ghouta',
       'Ansar al-Sharia (Syria)',
       'Jaish al-Haramoun' ] },
  { name: 'Ajnad al-Sham Islamic Union',
    allies: 
     [ 'Army of Mujahedeen',
       'Sham Legion',
       'Alweiat Al-Furqan',
       'Islamic Front (Syria)' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'Syrian Revolutionary Command Council',
       'Unified Military Command of Eastern Ghouta' ] },
  { name: 'Sham Legion',
    allies: 
     [ 'Ajnad al-Sham Islamic Union',
       'Army of Mujahedeen',
       'Alweiat Al-Furqan',
       'Islamic Front (Syria)' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'Syrian Revolutionary Command Council',
       'As-Safir',
       'Army of Conquest',
       'Fatah Halab' ] },
  { name: 'Army of Mujahedeen',
    allies: 
     [ 'Syria Revolutionaries Front',
       'Islamic Front (Syria)',
       'al-Nusra Front',
       'Ajnad al-Sham Islamic Union',
       'Sham Legion',
       'Alweiat Al-Furqan' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'Syrian Revolutionary Command Council',
       'Levant Front',
       'Fatah Halab' ] },
  { name: 'Suqour al-Ezz',
    allies: 
     [ 'Islamic State of Iraq and the Levant',
       'Green Battalion',
       'Harakat Sham al-Islam',
       'Jaish al-Muhajireen wal-Ansar',
       'Ahrar ash-Sham' ],
    opponents: [ 'Syrian Armed Forces' ],
    partof: [ 'al-Nusra Front' ] },
  { name: 'Syrian Resistance',
    allies: 
     [ 'Syrian Armed Forces',
       'National Defence Force (Syria)',
       'DHKP/C' ],
    opponents: 
     [ 'Free Syrian Army',
       'Al-Nusra Front',
       'Islamic State of Iraq and Levant' ],
    partof: [] },
  { name: 'Harakat Sham al-Islam',
    allies: 
     [ 'al-Nusra Front',
       'Ahrar ash-Sham',
       'Jaish al-Muhajireen wal-Ansar',
       'Islamic State of Iraq and the Levant' ],
    opponents: [ 'Syrian Armed Forces' ],
    partof: [ 'Jabhat Ansar al-Din' ] },
  { name: 'Jaysh al-Islam',
    allies: 
     [ 'Free Syrian Army',
       'Ahrar ash-Sham',
       'Ajnad al-Sham Islamic Union',
       'Army of Mujahedeen',
       'Alweiat Al-Furqan',
       'Sham Legion',
       'Jabhat al-Akrad' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Popular Front for the Liberation of Palestine – General Command',
       'Liwa Abu al-Fadhal al-Abbas',
       'Islamic State of Iraq and the Levant',
       'Jaysh al-Ummah',
       'Jabhat al-Nusra' ],
    partof: 
     [ 'Islamic Front (Syria)',
       'Mujahideen Shura Council (Syria)',
       'Syrian Revolutionary Command Council',
       'Fatah Halab',
       'Unified Military Command of Eastern Ghouta' ] },
  { name: 'Ahrar al-Jazeera',
    allies: 
     [ 'Al-Nusra Front',
       'Ghuraba al-Sham (jihadist group)',
       'Ahrar ash-Sham' ],
    opponents: [ 'Syrian Armed Forces', 'People\'s Protection Units' ],
    partof: [] },
  { name: 'al-Nusra Front',
    allies: 
     [ 'Islamic State of Iraq and the Levant',
       'Yarmouk Camp',
       'Islamic Front (Syria)',
       'Harakat Sham al-Islam',
       'Ajnad al-Sham Islamic Union',
       'Jund al-Aqsa',
       'Ansar al-Islam' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defence Forces (Syria)',
       'Ba\'ath Brigades',
       'Lebanese Armed Forces',
       'Islamic Front (Syria)',
       'Jaysh al-Islam',
       'Jaysh al-Islam',
       'Free Syrian Army',
       'Dawn of Freedom Brigades',
       'Syria Revolutionaries Front',
       'Hazzm Movement',
       '101st Division (Syrian rebel group)',
       'Southern Front (Syrian rebel group)',
       'Syrian Resistance',
       'Hezbollah',
       'Asa\'ib Ahl al-Haq',
       'Al-Abbas brigade',
       'Islamic State of Iraq and the Levant',
       'CNN',
       'Yarmouk Martyrs Brigade',
       'Jaysh al-Jihad' ],
    partof: 
     [ 'Al-Qaeda',
       'Mujahideen Shura Council (Syria)',
       'Army of Conquest',
       'Battle of Victory',
       'Ansar al-Sharia (Syria)',
       'Jaish al-Haramoun' ] },
  { name: 'Syriac Military Council',
    allies: [ 'People\'s Protection Units', 'Khabour Guards' ],
    opponents: [ 'Islamic State of Iraq and the Levant', 'al-Nusra Front' ],
    partof: [ 'Syriac Union Party (Syria)' ] },
  { name: 'Syrian Armed Forces',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Jaish al-Muhajireen wal-Ansar',
    allies: 
     [ 'Syria Revolutionaries Front',
       'Al-Nusra Front to Protect the Levant',
       'Islamic Front (Syria)',
       'Army of Mujahedeen',
       'Suqour al-Ezz',
       'Harakat Sham al-Islam',
       '13th Division (Syrian rebel group)' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [ 'Caucasus Emirate', 'Jabhat Ansar al-Din' ] },
  { name: 'Syrian Revolutionary Command Council',
    allies: [],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Fatah Halab',
    allies: [],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Jaish al-Haramoun',
    allies: [ 'Army of Conquest' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Ansar al-Sharia (Syria)',
    allies: [],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Islamic Front (Syria)',
    allies: 
     [ 'Syria Revolutionaries Front',
       'Army of Mujahedeen',
       'Ajnad al-Sham Islamic Union',
       'Sham Legion',
       'Alweiat Al-Furqan',
       'al-Nusra Front',
       'People\'s Protection Units' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defence Force (Syria)',
       'Ba\'ath Brigades',
       'Hezbollah',
       'Asa\'ib Ahl al-Haq',
       'Al-Abbas brigade',
       'Syrian Resistance',
       'Islamic State of Iraq and the Levant' ],
    partof: [ 'Levant Front' ] },
  { name: 'Army of Conquest',
    allies: [ 'Jaish al-Haramoun', 'Battle of Victory' ],
    opponents: 
     [ 'Islamic State of Iraq and the Levant',
       'Hezbollah',
       'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)' ],
    partof: [] },
  { name: 'United States Armed Forces',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Unified Military Command of Eastern Ghouta',
    allies: [],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Islamic State of Iraq and the Levant',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Syria Revolutionaries Front',
    allies: 
     [ 'Islamic Front (Syria)',
       'Army of Mujahedeen',
       'Jaish al-Muhajireen wal-Ansar',
       'al-Nusra Front' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Islamic State of Iraq and the Levant',
       'al-Nusra Front',
       'Jund al-Aqsa',
       'Yarmouk Martyrs Brigade' ],
    partof: 
     [ 'National Coalition for Syrian Revolutionary and Opposition Forces',
       'Syrian Revolutionary Command Council',
       'Southern Front (Syrian rebel group)',
       'The Revolutionary Army (Syrian rebel group)' ] },
  { name: 'Green Battalion',
    allies: [ 'Al-Nusra Front', 'Islamic State of Iraq and the Levant' ],
    opponents: [ 'Syrian Armed Forces', 'Hezbollah' ],
    partof: [ 'Jabhat Ansar al-Din' ] },
  { name: 'Levant Front',
    allies: 
     [ 'People\'s Protection Units',
       'Jabhat Ansar al-Din',
       'Jabhat al-Nusra',
       'International Business Times' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [ 'Fatah Halab' ] },
  { name: 'Jabhat Ansar al-Din',
    allies: [],
    opponents: [ 'Syrian Armed Forces' ],
    partof: [ 'Ansar al-Sharia (Syria)' ] },
  { name: 'Jabhat al-Akrad',
    allies: 
     [ 'Liwa Thuwwar al-Raqqa',
       'People\'s Protection Units',
       'Al-Tawhid Brigade',
       'Jaysh al-Islam' ],
    opponents: [ 'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'Euphrates Volcano',
       'The Revolutionary Army (Syrian rebel group)' ] },
  { name: 'Liwa Abu al-Fadhal al-Abbas',
    allies: 
     [ 'Syrian Armed Forces',
       'National Defense Force (Syria)',
       'Hezbollah',
       'Kata\'ib Hezbollah',
       'Iraqi Armed Forces' ],
    opponents: 
     [ 'Free Syrian Army',
       'Islamic Front (Syria)',
       'Al-Nusra Front',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Jaysh al-Ummah',
    allies: [ 'Syrian Armed Forces', 'National Defense Force (Syria)' ],
    opponents: [ 'Southern Front (Syrian rebel group)', 'Jaysh al-Islam' ],
    partof: [] },
  { name: 'Mujahideen Shura Council (Syria)',
    allies: [ 'Free Syrian Army' ],
    opponents: [ 'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Popular Front for the Liberation of Palestine – General Command',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Al-Nusra Front',
    allies: 
     [ 'Islamic State of Iraq and the Levant',
       'Yarmouk Camp',
       'Islamic Front (Syria)',
       'Harakat Sham al-Islam',
       'Ajnad al-Sham Islamic Union',
       'Jund al-Aqsa',
       'Ansar al-Islam' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defence Forces (Syria)',
       'Ba\'ath Brigades',
       'Lebanese Armed Forces',
       'Islamic Front (Syria)',
       'Jaysh al-Islam',
       'Jaysh al-Islam',
       'Free Syrian Army',
       'Dawn of Freedom Brigades',
       'Syria Revolutionaries Front',
       'Hazzm Movement',
       '101st Division (Syrian rebel group)',
       'Southern Front (Syrian rebel group)',
       'Syrian Resistance',
       'Hezbollah',
       'Asa\'ib Ahl al-Haq',
       'Al-Abbas brigade',
       'Islamic State of Iraq and the Levant',
       'CNN',
       'Yarmouk Martyrs Brigade',
       'Jaysh al-Jihad' ],
    partof: 
     [ 'Al-Qaeda',
       'Mujahideen Shura Council (Syria)',
       'Army of Conquest',
       'Battle of Victory',
       'Ansar al-Sharia (Syria)',
       'Jaish al-Haramoun' ] },
  { name: 'Jund al-Aqsa',
    allies: 
     [ 'Liwaa al-Umma',
       'Liwa al-Haqq (Idlib, Syria)',
       'Ahrar ash-Sham',
       'al-Nusra Front' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syria Revolutionaries Front',
       'Hazzm Movement',
       'Free Syrian Army',
       'United States',
       'Syrian opposition–Islamic State of Iraq and the Levant conflict',
       '2014 Hama offensive',
       '2014 Idlib offensive',
       'Al-Nusra Front–Syria Revolutionaries Front conflict',
       'Second Battle of Idlib' ],
    partof: 
     [ 'al-Nusra Front',
       'Muhajirin wa-Ansar Alliance',
       'Army of Conquest' ] },
  { name: 'Ba\'ath Brigades',
    allies: [ 'Syrian Armed Forces', 'National Defense Force (Syria)' ],
    opponents: 
     [ 'Free Syrian Army',
       'Islamic Front (Syria)',
       'al-Nusra Front',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'People\'s Protection Units',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Free Syrian Army',
    allies: 
     [ 'Islamic Front (Syria)',
       'People\'s Protection Units',
       'Syriac Military Council' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defence Force (Syria)',
       'al-Nusra Front',
       'Jund al-Aqsa',
       'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'National Coalition for Syrian Revolutionary and Opposition Forces',
       'Euphrates Volcano' ] },
  { name: 'Dawn of Freedom Brigades',
    allies: [ 'People\'s Protection Units' ],
    opponents: [ 'Islamic State of Iraq and the Levant', 'Al-Nusra Front' ],
    partof: 
     [ 'Free Syrian Army',
       'Euphrates Volcano',
       'The Revolutionary Army (Syrian rebel group)' ] },
  { name: '101st Division (Syrian rebel group)',
    allies: [ 'Islamic Front (Syria)', 'Al-Nusra Front' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'Free Syrian Army',
       'Syrian Revolutionary Command Council',
       'Fatah Halab' ] },
  { name: 'Hazzm Movement',
    allies: [],
    opponents: 
     [ 'Syrian Armed Forces',
       'Islamic State of Iraq and Syria',
       'Al-Nusra Front' ],
    partof: 
     [ 'Free Syrian Army',
       'Levant Front',
       'Syrian Revolutionary Command Council' ] },
  { name: 'National Defence Forces (Syria)',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Ansar al-Islam',
    allies: [ 'al-Nusra Front' ],
    opponents: 
     [ 'Iraqi Armed Forces',
       'Multi-National Force – Iraq',
       'Syrian Armed Forces',
       'Kurdish Peshmerga' ],
    partof: [] },
  { name: 'Jaysh al-Jihad',
    allies: [ 'Yarmouk Martyrs Brigade' ],
    opponents: 
     [ 'Ahrar ash-Sham',
       'Southern Front (Syrian rebel group)',
       'al-Nusra Front',
       'Jaysh al-Islam',
       'Alwiya al-Furqan' ],
    partof: [ 'Islamic State of Iraq and the Levant' ] },
  { name: 'Yarmouk Martyrs Brigade',
    allies: [ 'Jaysh al-Jihad' ],
    opponents: 
     [ 'al-Nusra Front',
       'Syria Revolutionaries Front',
       'Islamic Muthanna Movement',
       'Syrian Armed Forces',
       'National Defense Force (Syria)' ],
    partof: [ 'Islamic State of Iraq and the Levant' ] },
  { name: 'Lebanese Armed Forces',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Asa\'ib Ahl al-Haq',
    allies: 
     [ 'Iraq',
       'Kata\'ib Hezbollah',
       'Promised Day Brigades',
       'Special Groups (Iraq)',
       'Liwa Abu al-Fadhal al-Abbas',
       'Shabiha' ],
    opponents: 
     [ 'Multi-National Force – Iraq',
       'Islamic State of Iraq and the Levant',
       'Free Syrian Army',
       'Authenticity and Development Front',
       'Islamic Front (Syria)',
       'al-Nusrah Front',
       'Islamic State of Iraq and the Levant' ],
    partof: [ 'Popular Mobilization Forces (Iraq)' ] },
  { name: 'Battle of Victory',
    allies: [ 'Free Syrian Army', 'Alwiya al-Furqan', 'Army of Mujahedeen' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Khabour Guards',
    allies: [ 'Gozarto Protection Forces' ],
    opponents: [ 'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: '13th Division (Syrian rebel group)',
    allies: 
     [ 'Islamic Front (Syria)',
       'Al-Nusra Front',
       'Jaish al-Muhajireen wal-Ansar' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'Free Syrian Army',
       'Syrian Revolutionary Command Council',
       'Fatah Halab' ] },
  { name: 'Hezbollah', allies: [], opponents: [], partof: [] },
  { name: 'Caucasus Emirate',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Syrian Army', allies: [], opponents: [], partof: [] },
  { name: 'Syrian Arab Air Force',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Al-Qaeda',
    allies: 
     [ 'Taliban',
       'Tehrik-i-Taliban Pakistan',
       'Islamic Movement of Uzbekistan',
       'East Turkestan Islamic Movement',
       'Lashkar-e-Taiba',
       'Jaish-e-Mohammed',
       'Jemaah Islamiyah',
       'Abu Sayyaf',
       'Caucasus Emirate',
       'Egyptian Islamic Jihad' ],
    opponents: [],
    partof: [ 'Taliban', 'Islamic Emirate of Afghanistan' ] },
  { name: 'The Revolutionary Army (Syrian rebel group)',
    allies: 
     [ 'Islamic Front (Syria)',
       'People\'s Protection Units',
       'New Syrian Forces' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant',
       'al-Nusra Front' ],
    partof: [ 'Free Syrian Army', 'Euphrates Volcano' ] },
  { name: 'Euphrates Volcano',
    allies: [ 'Combined Joint Task Force – Operation Inherent Resolve' ],
    opponents: [ 'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Liwa Thuwwar al-Raqqa',
    allies: 
     [ 'Euphrates Islamic Liberation Front',
       'Liwa Ahrar Souriya',
       'People\'s Protection Units',
       'Farouq Brigades',
       'Jabhat al-Akrad',
       'Jihad in the Path of God Brigade' ],
    opponents: 
     [ 'Islamic State of Iraq and the Levant',
       'Syrian Armed Forces' ],
    partof: [ 'Free Syrian Army', 'Jabhat al-Nusra', 'Euphrates Volcano' ] },
  { name: 'Liwaa al-Umma',
    allies: [ 'Liwa al-Haqq (Idlib, Syria)', 'Jund al-Aqsa' ],
    opponents: [ 'Syrian Armed Forces', 'National Defense Force (Syria)' ],
    partof: [ 'Free Syrian Army', 'Muhajirin wa-Ansar Alliance' ] },
  { name: 'Kata\'ib Hezbollah',
    allies: 
     [ 'File:InfoboxHez.PNG',
       'Hezbollah',
       'Asa\'ib Ahl al-Haq',
       'Promised Day Brigades',
       'Special Groups (Iraq)',
       'Liwa Abu al-Fadhal al-Abbas',
       'Multinational force in Iraq' ],
    opponents: [ 'Islamic State of Iraq and the Levant' ],
    partof: [ 'Popular Mobilization Forces (Iraq)' ] },
  { name: 'Liwa al-Haqq (Idlib, Syria)',
    allies: [ 'Liwaa al-Umma', 'Jund al-Aqsa' ],
    opponents: [ 'Syrian Armed Forces' ],
    partof: 
     [ 'Muhajirin wa-Ansar Alliance',
       'Army of Conquest',
       'Fatah Halab' ] },
  { name: 'National Coalition for Syrian Revolutionary and Opposition Forces',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Al-Tawhid Brigade',
    allies: 
     [ 'Al-Nusra Front to Protect the Levant',
       'Ahrar ash-Sham',
       'Jaysh al-Islam',
       'Ajnad al-Sham Islamic Union',
       'Army of Mujahedeen',
       'Alwiya al-Furqan',
       'Sham Legion' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Popular Protection Units',
       'Ghuraba al-Sham (moderate group)',
       'Hezbollah',
       'Islamic State of Iraq and the Levant' ],
    partof: 
     [ 'Free Syrian Army',
       'Syrian Revolutionary Command Council',
       'Syrian Islamic Liberation Front',
       'Islamic Front (Syria)' ] },
  { name: 'Muhajirin wa-Ansar Alliance',
    allies: [ 'al-Nusra Front' ],
    opponents: [ 'Syrian Armed Forces' ],
    partof: [] },
  { name: 'Alwiya al-Furqan',
    allies: [ 'Free Syrian Army', 'Islamic Front (Syria)' ],
    opponents: [ 'Syrian Armed Forces' ],
    partof: [ 'Tajammu Ansar al-Islam', 'Fatah Halab' ] },
  { name: 'Islamic Muthanna Movement',
    allies: 
     [ 'al-Nusra Front',
       'Islamic Front (Syria)',
       'Syria Revolutionaries Front',
       'Southern Front (Syrian rebel group)' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'National Defense Force (Syria)',
       'Yarmouk Martyrs Brigade' ],
    partof: [] },
  { name: 'Iraqi Armed Forces',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Authenticity and Development Front',
    allies: [ 'Free Syrian Army', 'Islamic Front (Syria)', 'Al-Nusra Front' ],
    opponents: 
     [ 'Islamic State of Iraq and the Levant',
       'Syrian Armed Forces' ],
    partof: 
     [ 'Mujahideen Shura Council (Syria)',
       'Syrian Revolutionary Command Council',
       'Levant Front',
       'Fatah Halab' ] },
  { name: 'Special Groups (Iraq)',
    allies: [ 'Mahdi Army' ],
    opponents: [],
    partof: [ 'Mahdi Army', 'Iraqi insurgency (Iraq War)' ] },
  { name: 'Shabiha',
    allies: [ 'Syrian Armed Forces', 'National Defense Force (Syria)' ],
    opponents: 
     [ 'Free Syrian Army',
       'Al-Nusra Front',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Multi-National Force – Iraq',
    allies: 
     [ 'NATO Training Mission – Iraq',
       'United Nations Assistance Mission for Iraq' ],
    opponents: 
     [ 'File:Flag of JTJ.svg',
       'Jama\'at al-Tawhid wal-Jihad',
       'al-Qaeda in Iraq',
       'Mujahideen Shura Council (Iraq)',
       'Islamic State in Iraq and the Levant' ],
    partof: [] },
  { name: 'Iraq', allies: [], opponents: [], partof: [] },
  { name: 'Jemaah Islamiyah',
    allies: [ 'Taliban', 'File:Flag of al-Qaeda.svg', 'al-Qaeda' ],
    opponents: 
     [ 'Australia',
       'Indonesia',
       'Malaysia',
       'Philippines',
       'Singapore',
       'Thailand',
       'United States' ],
    partof: [] },
  { name: 'Islamic Movement of Uzbekistan',
    allies: 
     [ 'Taliban',
       'Tehrik-i-Taliban Pakistan',
       'al-Qaeda',
       'East Turkestan Islamic Movement',
       'Jamestown Foundation',
       'Caucasus Emirate',
       'United Nations' ],
    opponents: 
     [ 'File:Flag of Uzbekistan.svg',
       'Uzbekistan',
       'File:Flag of Russia.svg',
       'Russia',
       'File:Flag of United States.svg',
       'United States',
       'File:Flag of Pakistan.svg',
       'Pakistan',
       'File:Flag of Afghanistan.svg',
       'Afghanistan',
       'File:Flag of the International Security Assistance Force.svg',
       'International Security Assistance Force' ],
    partof: [] },
  { name: 'East Turkestan Islamic Movement',
    allies: 
     [ 'Tehrik-i-Taliban Pakistan',
       'al-Qaeda',
       'Nusra Front',
       'Islamic Movement of Uzbekistan',
       'Jamestown Foundation' ],
    opponents: [ 'File:Flag of China.svg', 'China' ],
    partof: [] },
  { name: 'Taliban',
    allies: 
     [ 'Tehrik-i-Taliban Pakistan',
       'Haqqani network',
       'al-Qaeda',
       'Tehreek-e-Nafaz-e-Shariat-e-Mohammadi',
       'Caucasian Front (Chechen War)',
       'Lashkar-e-Jhangvi',
       'Hezb-e-Islami Gulbuddin' ],
    opponents: 
     [ 'Islamic Republic of Afghanistan',
       'North Atlantic Treaty Organization',
       'International Security Assistance Force',
       'Islamic State of Iraq and the Levant',
       'Jamiat-e Islami',
       'National Islamic Movement of Afghanistan',
       'Hezbe Wahdat' ],
    partof: [] },
  { name: 'Euphrates Islamic Liberation Front',
    allies: 
     [ 'Liwa Thuwwar al-Raqqa',
       'Liwa Ahrar Souriya',
       'People\'s Protection Units',
       'Jabhat al-Akrad',
       'Jihad in the Path of God Brigade' ],
    opponents: 
     [ 'Islamic State of Iraq and the Levant',
       'Syrian Armed Forces' ],
    partof: [ 'Free Syrian Army' ] },
  { name: 'Combined Joint Task Force – Operation Inherent Resolve',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'New Syrian Forces',
    allies: 
     [ 'The Revolutionary Army (Syrian rebel group)',
       'People\'s Protection Units' ],
    opponents: [ 'Islamic State of Iraq and the Levant', 'al-Nusra Front' ],
    partof: [ 'Free Syrian Army' ] },
  { name: 'Lashkar-e-Taiba', allies: [], opponents: [], partof: [] },
  { name: 'Liwa Ahrar Souriya',
    allies: 
     [ 'Euphrates Islamic Liberation Front',
       'Liwa Thuwwar al-Raqqa',
       'People\'s Protection Units' ],
    opponents: 
     [ 'Islamic State of Iraq and the Levant',
       'Syrian Armed Forces' ],
    partof: [ 'Free Syrian Army' ] },
  { name: 'Tehrik-i-Taliban Pakistan',
    allies: 
     [ 'Taliban',
       'Haqqani network',
       'Al-Qaeda',
       'Tehreek-e-Nafaz-e-Shariat-e-Mohammadi',
       'File:Etim tip logo.JPG',
       'East Turkestan Islamic Movement',
       'Islamic Movement of Uzbekistan',
       'Sipah-e-Sahaba Pakistan',
       'Lashkar-e-Jhangvi',
       'Harkat-ul-Jihad al-Islami' ],
    opponents: [ 'Islamic Republic of Pakistan', 'United States of America' ],
    partof: [] },
  { name: 'Islamic Emirate of Afghanistan',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Jihad in the Path of God Brigade',
    allies: 
     [ 'Euphrates Islamic Liberation Front',
       'Liwa Thuwwar al-Raqqa',
       'Euphrates Volcano' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Islamic State of Iraq and the Levant' ],
    partof: [ 'Free Syrian Army', 'Euphrates Volcano', 'Jaish al-Salam' ] },
  { name: 'Abu Sayyaf',
    allies: [ '14K Triad', 'File:Flag of Jihad.svg', 'al-Qaeda' ],
    opponents: [],
    partof: [] },
  { name: 'Farouq Brigades',
    allies: 
     [ 'Suqour al-Sham',
       'Liwa al-Islam',
       'Liwa Thuwwar al-Raqqa',
       'People\'s Protection Units' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Islamic State of Iraq and the Levant' ],
    partof: [ 'Free Syrian Army', 'Syrian Islamic Liberation Front' ] },
  { name: 'Syrian Islamic Liberation Front',
    allies: 
     [ 'Al-Nusra Front to Protect the Levant',
       'Ahrar ash-Sham',
       'Free Syrian Army' ],
    opponents: 
     [ 'Syrian Armed Forces',
       'Ghuraba al-Sham (moderate group)',
       'People\'s Protection Units',
       'Shabiha' ],
    partof: [] },
  { name: 'Jama\'at al-Tawhid wal-Jihad',
    allies: [ 'Ansar al-Islam' ],
    opponents: 
     [ 'Multinational force in Iraq',
       'Iraq',
       'Iraqi security forces',
       'Kurds',
       'Shia',
       'Jordan',
       'United Nations' ],
    partof: [] },
  { name: 'Mujahideen Shura Council (Iraq)',
    allies: [],
    opponents: [ 'Multi-National Force – Iraq', 'Republic of Iraq' ],
    partof: [ 'Al-Qaeda' ] },
  { name: 'United Nations', allies: [], opponents: [], partof: [] },
  { name: 'Australia', allies: [], opponents: [], partof: [] },
  { name: 'Indonesia', allies: [], opponents: [], partof: [] },
  { name: 'Jamiat-e Islami', allies: [], opponents: [], partof: [] },
  { name: 'Singapore', allies: [], opponents: [], partof: [] },
  { name: 'Tehreek-e-Nafaz-e-Shariat-e-Mohammadi',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'National Islamic Movement of Afghanistan',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Thailand', allies: [], opponents: [], partof: [] },
  { name: 'Philippines', allies: [], opponents: [], partof: [] },
  { name: 'Lashkar-e-Jhangvi',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'al-Qaeda',
    allies: 
     [ 'Taliban',
       'Tehrik-i-Taliban Pakistan',
       'Islamic Movement of Uzbekistan',
       'East Turkestan Islamic Movement',
       'Lashkar-e-Taiba',
       'Jaish-e-Mohammed',
       'Jemaah Islamiyah',
       'Abu Sayyaf',
       'Caucasus Emirate',
       'Egyptian Islamic Jihad' ],
    opponents: [],
    partof: [ 'Taliban', 'Islamic Emirate of Afghanistan' ] },
  { name: 'Malaysia', allies: [], opponents: [], partof: [] },
  { name: 'Uzbekistan', allies: [], opponents: [], partof: [] },
  { name: 'Jaish al-Salam',
    allies: [],
    opponents: 
     [ 'Syrian Armed Forces',
       'Syrian Army',
       'Syrian Arab Air Force',
       'National Defense Force (Syria)',
       'Islamic State of Iraq and the Levant' ],
    partof: [] },
  { name: 'Afghanistan', allies: [], opponents: [], partof: [] },
  { name: 'Pakistan', allies: [], opponents: [], partof: [] },
  { name: 'Haqqani network',
    allies: 
     [ 'Taliban',
       'Tehrik-i-Taliban Pakistan',
       'Tehreek-e-Nafaz-e-Shariat-e-Mohammadi' ],
    opponents: 
     [ 'Islamic Republic of Afghanistan',
       'File:Afghan National Army emblem.svg',
       'Afghan National Army',
       'File:Afghan National Army emblem.svg',
       'Afghan Air Force',
       'File:ANP logo English.svg',
       'Afghan National Police',
       'North Atlantic Treaty Organization',
       'File:Flag of the International Security Assistance Force.svg',
       'International Security Assistance Force' ],
    partof: [] },
  { name: 'China', allies: [], opponents: [], partof: [] },
  { name: 'Hezbe Wahdat', allies: [], opponents: [], partof: [] },
  { name: 'Russia', allies: [], opponents: [], partof: [] },
  { name: 'International Security Assistance Force',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Kurds', allies: [], opponents: [], partof: [] },
  { name: 'Jordan', allies: [], opponents: [], partof: [] },
  { name: 'Afghan National Army',
    allies: [],
    opponents: [],
    partof: [] },
  { name: 'Japan', allies: [], opponents: [], partof: [] },
  { name: 'Italy', allies: [], opponents: [], partof: [] } ]
