var nodes = [
  { name: 'Ahrar ash-Sham' },
  { name: 'Ajnad al-Sham Islamic Union' },
  { name: 'Sham Legion' },
  { name: 'Army of Mujahedeen' },
  { name: 'Suqour al-Ezz' },
  { name: 'Syrian Resistance' },
  { name: 'Harakat Sham al-Islam' },
  { name: 'Jaysh al-Islam' },
  { name: 'Ahrar al-Jazeera' },
  { name: 'al-Nusra Front' },
  { name: 'Syriac Military Council' },
  { name: 'Syrian Armed Forces' },
  { name: 'Jaish al-Muhajireen wal-Ansar' },
  { name: 'Syrian Revolutionary Command Council' },
  { name: 'Fatah Halab' },
  { name: 'Jaish al-Haramoun' },
  { name: 'Ansar al-Sharia (Syria)' },
  { name: 'Islamic Front (Syria)' },
  { name: 'Army of Conquest' },
  { name: 'United States Armed Forces' },
  { name: 'Unified Military Command of Eastern Ghouta' },
  { name: 'Islamic State of Iraq and the Levant' },
  { name: 'Syria Revolutionaries Front' },
  { name: 'Green Battalion' },
  { name: 'Levant Front' },
  { name: 'Jabhat Ansar al-Din' },
  { name: 'Jabhat al-Akrad' },
  { name: 'Liwa Abu al-Fadhal al-Abbas' },
  { name: 'Jaysh al-Ummah' },
  { name: 'Mujahideen Shura Council (Syria)' },
  { name: 'Popular Front for the Liberation of Palestine – General Command' },
  { name: 'Al-Nusra Front' },
  { name: 'Jund al-Aqsa' },
  { name: 'Ba\'ath Brigades' },
  { name: 'People\'s Protection Units' },
  { name: 'Free Syrian Army' },
  { name: 'Dawn of Freedom Brigades' },
  { name: '101st Division (Syrian rebel group)' },
  { name: 'Hazzm Movement' },
  { name: 'National Defence Forces (Syria)' },
  { name: 'Ansar al-Islam' },
  { name: 'Jaysh al-Jihad' },
  { name: 'Yarmouk Martyrs Brigade' },
  { name: 'Lebanese Armed Forces' },
  { name: 'Asa\'ib Ahl al-Haq' },
  { name: 'Battle of Victory' },
  { name: 'Khabour Guards' },
  { name: '13th Division (Syrian rebel group)' },
  { name: 'Hezbollah' },
  { name: 'Caucasus Emirate' },
  { name: 'Syrian Army' },
  { name: 'Syrian Arab Air Force' },
  { name: 'Al-Qaeda' },
  { name: 'The Revolutionary Army (Syrian rebel group)' },
  { name: 'Euphrates Volcano' },
  { name: 'Liwa Thuwwar al-Raqqa' },
  { name: 'Liwaa al-Umma' },
  { name: 'Kata\'ib Hezbollah' },
  { name: 'Liwa al-Haqq (Idlib, Syria)' },
  { name: 'National Coalition for Syrian Revolutionary and Opposition Forces' },
  { name: 'Al-Tawhid Brigade' },
  { name: 'Muhajirin wa-Ansar Alliance' },
  { name: 'Alwiya al-Furqan' },
  { name: 'Islamic Muthanna Movement' },
  { name: 'Iraqi Armed Forces' },
  { name: 'Authenticity and Development Front' },
  { name: 'Special Groups (Iraq)' },
  { name: 'Shabiha' },
  { name: 'Multi-National Force – Iraq' },
  { name: 'Iraq' },
  { name: 'Jemaah Islamiyah' },
  { name: 'Islamic Movement of Uzbekistan' },
  { name: 'East Turkestan Islamic Movement' },
  { name: 'Taliban' },
  { name: 'Euphrates Islamic Liberation Front' },
  { name: 'Combined Joint Task Force – Operation Inherent Resolve' },
  { name: 'New Syrian Forces' },
  { name: 'Lashkar-e-Taiba' },
  { name: 'Liwa Ahrar Souriya' },
  { name: 'Tehrik-i-Taliban Pakistan' },
  { name: 'Islamic Emirate of Afghanistan' },
  { name: 'Jihad in the Path of God Brigade' },
  { name: 'Abu Sayyaf' },
  { name: 'Farouq Brigades' },
  { name: 'Syrian Islamic Liberation Front' },
  { name: 'Jama\'at al-Tawhid wal-Jihad' },
  { name: 'Mujahideen Shura Council (Iraq)' },
  { name: 'United Nations' },
  { name: 'Australia' },
  { name: 'Indonesia' },
  { name: 'Jamiat-e Islami' },
  { name: 'Singapore' },
  { name: 'Tehreek-e-Nafaz-e-Shariat-e-Mohammadi' },
  { name: 'National Islamic Movement of Afghanistan' },
  { name: 'Thailand' },
  { name: 'Philippines' },
  { name: 'Lashkar-e-Jhangvi' },
  { name: 'al-Qaeda' },
  { name: 'Malaysia' },
  { name: 'Uzbekistan' },
  { name: 'Jaish al-Salam' },
  { name: 'Afghanistan' },
  { name: 'Pakistan' },
  { name: 'Haqqani network' },
  { name: 'China' },
  { name: 'Hezbe Wahdat' },
  { name: 'Russia' },
  { name: 'International Security Assistance Force' },
  { name: 'Kurds' },
  { name: 'Jordan' },
  { name: 'Afghan National Army' },
  { name: 'Japan' },
  { name: 'Italy' }
];
